# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.8
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setPointSize(22)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("empty.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(320, 5, 480, 311))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.albumLabel = QtGui.QLabel(self.frame_2)
        self.albumLabel.setGeometry(QtCore.QRect(10, 60, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.albumLabel.setFont(font)
        self.albumLabel.setScaledContents(True)
        self.albumLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.albumLabel.setObjectName(_fromUtf8("albumLabel"))
        self.tagsLabel = QtGui.QLabel(self.frame_2)
        self.tagsLabel.setGeometry(QtCore.QRect(10, 150, 431, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(50)
        font.setBold(False)
        self.tagsLabel.setFont(font)
        self.tagsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tagsLabel.setFrameShape(QtGui.QFrame.NoFrame)
        self.tagsLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.tagsLabel.setMidLineWidth(0)
        self.tagsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tagsLabel.setObjectName(_fromUtf8("tagsLabel"))
        self.yearLabel = QtGui.QLabel(self.frame_2)
        self.yearLabel.setGeometry(QtCore.QRect(10, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setWeight(50)
        font.setBold(False)
        self.yearLabel.setFont(font)
        self.yearLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yearLabel.setScaledContents(True)
        self.yearLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.yearLabel.setObjectName(_fromUtf8("yearLabel"))
        self.artistLabel = QtGui.QLabel(self.frame_2)
        self.artistLabel.setGeometry(QtCore.QRect(10, 20, 461, 36))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setWeight(75)
        font.setItalic(False)
        font.setBold(True)
        self.artistLabel.setFont(font)
        self.artistLabel.setScaledContents(True)
        self.artistLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.artistLabel.setObjectName(_fromUtf8("artistLabel"))
        self.songsLabel = QtGui.QLabel(self.frame_2)
        self.songsLabel.setGeometry(QtCore.QRect(310, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setWeight(50)
        font.setBold(False)
        self.songsLabel.setFont(font)
        self.songsLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.songsLabel.setScaledContents(True)
        self.songsLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songsLabel.setObjectName(_fromUtf8("songsLabel"))
        self.lcdcurrent = QtGui.QLCDNumber(self.frame_2)
        self.lcdcurrent.setGeometry(QtCore.QRect(310, 260, 71, 31))
        self.lcdcurrent.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdcurrent.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdcurrent.setSmallDecimalPoint(False)
        self.lcdcurrent.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdcurrent.setObjectName(_fromUtf8("lcdcurrent"))
        self.songLabel = QtGui.QLabel(self.frame_2)
        self.songLabel.setGeometry(QtCore.QRect(10, 200, 451, 36))
        font = QtGui.QFont()
        font.setPointSize(19)
        self.songLabel.setFont(font)
        self.songLabel.setScaledContents(True)
        self.songLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.songLabel.setObjectName(_fromUtf8("songLabel"))
        self.lcdtotal = QtGui.QLCDNumber(self.frame_2)
        self.lcdtotal.setGeometry(QtCore.QRect(390, 260, 71, 31))
        self.lcdtotal.setFrameShape(QtGui.QFrame.NoFrame)
        self.lcdtotal.setFrameShadow(QtGui.QFrame.Plain)
        self.lcdtotal.setSmallDecimalPoint(False)
        self.lcdtotal.setMode(QtGui.QLCDNumber.Dec)
        self.lcdtotal.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdtotal.setObjectName(_fromUtf8("lcdtotal"))
        self.listWidget = QtGui.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(320, 0, 480, 430))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.listWidget.setFont(font)
        self.listWidget.setFrameShape(QtGui.QFrame.NoFrame)
        self.listWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.listWidget.setLineWidth(0)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(360, 330, 411, 91))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.playButton = QtGui.QPushButton(self.frame)
        self.playButton.setGeometry(QtCore.QRect(110, 10, 91, 71))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.nextButton = QtGui.QPushButton(self.frame)
        self.nextButton.setGeometry(QtCore.QRect(310, 10, 91, 71))
        self.nextButton.setObjectName(_fromUtf8("nextButton"))
        self.stopButton = QtGui.QPushButton(self.frame)
        self.stopButton.setGeometry(QtCore.QRect(210, 10, 91, 71))
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.previousButton = QtGui.QPushButton(self.frame)
        self.previousButton.setGeometry(QtCore.QRect(9, 10, 91, 71))
        self.previousButton.setObjectName(_fromUtf8("previousButton"))
        self.artistsButton = QtGui.QPushButton(self.centralwidget)
        self.artistsButton.setGeometry(QtCore.QRect(20, 340, 141, 71))
        self.artistsButton.setObjectName(_fromUtf8("artistsButton"))
        self.playlistButton = QtGui.QPushButton(self.centralwidget)
        self.playlistButton.setEnabled(False)
        self.playlistButton.setGeometry(QtCore.QRect(170, 340, 141, 71))
        self.playlistButton.setObjectName(_fromUtf8("playlistButton"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 40))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMenu = QtGui.QMenu(self.menubar)
        self.menuMenu.setObjectName(_fromUtf8("menuMenu"))
        MainWindow.setMenuBar(self.menubar)
        self.actionClearRefresh = QtGui.QAction(MainWindow)
        self.actionClearRefresh.setEnabled(False)
        self.actionClearRefresh.setObjectName(_fromUtf8("actionClearRefresh"))
        self.actionHelp = QtGui.QAction(MainWindow)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setCheckable(True)
        self.actionConnect.setChecked(False)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionConfigure = QtGui.QAction(MainWindow)
        self.actionConfigure.setObjectName(_fromUtf8("actionConfigure"))
        self.actionFM_Radio = QtGui.QAction(MainWindow)
        self.actionFM_Radio.setCheckable(True)
        self.actionFM_Radio.setEnabled(False)
        self.actionFM_Radio.setObjectName(_fromUtf8("actionFM_Radio"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuMenu.addAction(self.actionConfigure)
        self.menuMenu.addAction(self.actionClearRefresh)
        self.menuMenu.addAction(self.actionFM_Radio)
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "...MaAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.albumLabel.setText(QtGui.QApplication.translate("MainWindow", "by nesnomis@gmail.com", None, QtGui.QApplication.UnicodeUTF8))
        self.tagsLabel.setText(QtGui.QApplication.translate("MainWindow", "Tags:", None, QtGui.QApplication.UnicodeUTF8))
        self.yearLabel.setText(QtGui.QApplication.translate("MainWindow", "Year: 0000", None, QtGui.QApplication.UnicodeUTF8))
        self.artistLabel.setText(QtGui.QApplication.translate("MainWindow", "MaAMP", None, QtGui.QApplication.UnicodeUTF8))
        self.songsLabel.setText(QtGui.QApplication.translate("MainWindow", "Songs: 00/00", None, QtGui.QApplication.UnicodeUTF8))
        self.songLabel.setText(QtGui.QApplication.translate("MainWindow", "Song...", None, QtGui.QApplication.UnicodeUTF8))
        self.playButton.setText(QtGui.QApplication.translate("MainWindow", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.nextButton.setText(QtGui.QApplication.translate("MainWindow", "Next", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.previousButton.setText(QtGui.QApplication.translate("MainWindow", "Prev", None, QtGui.QApplication.UnicodeUTF8))
        self.artistsButton.setText(QtGui.QApplication.translate("MainWindow", "Artists", None, QtGui.QApplication.UnicodeUTF8))
        self.playlistButton.setText(QtGui.QApplication.translate("MainWindow", "Playlists", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMenu.setTitle(QtGui.QApplication.translate("MainWindow", "Menu", None, QtGui.QApplication.UnicodeUTF8))
        self.actionClearRefresh.setText(QtGui.QApplication.translate("MainWindow", "Clear/Refresh cache", None, QtGui.QApplication.UnicodeUTF8))
        self.actionHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConnect.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigure.setText(QtGui.QApplication.translate("MainWindow", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFM_Radio.setText(QtGui.QApplication.translate("MainWindow", "Enable FM", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

